spring_profiles: hsqldb
admin:
  client_secret: adminsecret

logging:
  level:
    org.springframework.security: DEBUG

oauth:
  clients:
    admin:
      secret: adminsecret
      authorized-grant-types: authorization_code,client_credentials,refresh_token,password
      scope: openid,scim.read,scim.write
      authorities: uaa.admin,clients.read,clients.write,clients.secret
    dataflow:
      authorized-grant-types: authorization_code,client_credentials,refresh_token,password,implicit
      secret: d@d@fl0w
      scope: openid,password.write,scim.userids,dataflow.view,dataflow.deploy,dataflow.destroy,dataflow.manage,dataflow.modify,dataflow.schedule,dataflow.create
      authorities: uaa.resource,dataflow.create,dataflow.deploy,dataflow.destroy,dataflow.manage,dataflow.view,dataflow.modify,dataflow.schedule
      autoapprove:
        - openid
        - dataflow.view
        - dataflow.deploy
        - dataflow.destroy
        - dataflow.manage
        - dataflow.modify
        - dataflow.schedule
        - dataflow.create
      redirect-uri: http://localhost:9393/login/oauth2/code/dataflow
scim:
  groups:
    dataflow.create: SCDF Dataflow Create
    dataflow.deploy: SCDF Dataflow Deploy
    dataflow.destroy: SCDF Dataflow Destroy
    dataflow.manage: SCDF Dataflow Manage
    dataflow.view: SCDF Dataflow View
    dataflow.modify: SCDF Dataflow Modify
    dataflow.schedule: SCDF Dataflow Schedule
    clients.admin: Create, modify and delete OAuth clients
    clients.write: Create and modify OAuth clients
    clients.read: Read information about OAuth clients
    clients.secret: Change the password of an OAuth client
    scim.write: Create, modify and delete SCIM entities, i.e. users and groups
    scim.read: Read all SCIM entities, i.e. users and groups
    scim.create: Create users
    scim.userids: Read user IDs and retrieve users by ID
    scim.zones: Control a user's ability to manage a zone
    scim.invite: Send invitations to users
    password.write: Change your password
    oauth.approval: Manage approved scopes
    oauth.login: Authenticate users outside of the UAA
    openid: Access profile information, i.e. email, first and last name, and phone number
    groups.update: Update group information and memberships
    uaa.user: Act as a user in the UAA
    uaa.resource: Serve resources protected by the UAA
    uaa.admin: Act as an administrator throughout the UAA
    uaa.none: Forbid acting as a user
    uaa.offline_token: Allow offline access

  users:
    - admin|adminsecret|Admin User|admin@test.org|openid,scim.read,scim.write|uaa.admin
    - dataflow|d@d@fl0w|SCDF Admin|test@test.org|openid|dataflow.create,dataflow.deploy,dataflow.destroy,dataflow.manage,dataflow.view,dataflow.modify,dataflow.schedule|uaa

jwt:
  token:
    signing-key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDlC70BSZ6kcsAD
      YyNCSyirp88DbSn4ZF7h4t4bjxj/s7xxOMV6MxLbu7C4zicbMzAvPVKVHvRILxqq
      s/0liEA/AxIea9xdVjbWF2t5lIOAesO9OMpZwvnfmcqaQW+rAX+JKt/rbq6A9cox
      185ZZOSMGTHvyXVuqmwsLS5b1vYWc/BvneFxlHV5qSd05NIb8mGONCpCTB0ZsBR7
      xnd2fHQwxZzoIf665TIJNz7tgTv8X+xARHOX1lekgJ63SpGLhegdCp7VwIG0jd41
      DxJ9c8yZw++6dJiTey2+ixG/3JjdXyW8dMHtkV4nQkjaJj461kltbGHXvQmJWISd
      lBEVzyVJAgMBAAECggEAFEQydZY023qBzersOECb49Bl1fjx8UC5pTAPP2NX2Ww8
      Z3eYAETbotCxMDD22dvGJC/qCjgickP6DpJS0GAwGxiOS7Mh3P+0u23NZy/CZlBh
      LcbZdLwhTZfMiv3w6lx9aJQqxairTSLdFgWb2bdpLOefzlvw2u6+bTbpjAZxtjEM
      0u0JG+rJB7l3F7uqN7J5YrpoEN5JSWIPw1GxVZ/qsEB/V2/EqppbRPS/a6LCZMWH
      My+viexny5aF62ZX4rTz6tW5YknQtqyWkhxDIAm7H7oIYbyg4Tt8owmdWMCfq+Mc
      MMWP9hbS15tLsCI0XfA3dm0kD0rfR44Zk7DZhne9ZwKBgQD5Ui2GDXvpo7vOIZGO
      GABsgKJ3wUosi4WRqfaia2YYdEYdI7SrhdGqXcE/3HAvUb2/GeWoqkvznyP9CTpO
      sYMYwh35o3vZMvwZVqioKVC5DowW9lyvBSYevInYLSy8VV2LtwGUKEpoAhvdpKKN
      f/ZMHrK/V/TEjaYBL+uQMhhnWwKBgQDrLoPj8k/onfqHB9/U0NCOeA2VE0ekATCe
      cE0Etxgjy3wrUyB0GjZBzvCCW2jElK5oApvrMcO8MJUNBNoWd5XfS0/vwJ4/Kjnx
      XgkufTbxT1GYIWl2B6kza6bW43++qlyz2FP8c7Ius0Rs9LnyXrb9I6uJrymFjvgT
      WU1rR8SrKwKBgQDqKTR4YtGubglFYGHEguZjAa2VrARuMdwRIwBxK02ISixP0ekt
      71EsIUIPKIp05uC/SyNXdho/hYfXb4NDxZTK/AYLIHCBXlFHuwxMZAFczTzllB0Y
      hE15MLqGPmd1uvdQ8WCaNf0sEk75rFa/bx9z/qEC9Sj+Mctn8gncNDCXYQKBgF+4
      dPHoA+IXuooPCGkj/F6gOlb8m+ICofk6l/5dTzPydD1l/gWDTaYHRhiof8HTChFH
      TpKxlIsZ8vBzkxgl4BgcHRLmAQKQezjkHzSOvjgFIp6aqsPhZlqJbER2H95IlKaW
      W8iahmE/kZAPI0ekiTIKvJyzcGDtycaGSF5rvX41AoGADRSl6JGwGDMNcvH/L4iC
      6h6dVKrpl+cUOlzEYvsHKPloLcWSr4Od8NtJ9gidFxXVZoENmiR6JsDBQ7G6z1nW
      GflSBQXPw1bwzpIWwB15Mz/UtmLlLbyPw7qih2cXyd8+jZT+2L6rhtmKh33BAcbK
      0DiVp3pp+z0HYbfIvMPDbDk=
      -----END PRIVATE KEY-----
uaa:
  # The hostname of the UAA that this login server will connect to
  url: http://localhost:8080/uaa
  token:
    url: http://localhost:8080/uaa/oauth/token
  approvals:
    url: http://localhost:8080/uaa/approvals
  login:
    url: http://localhost:8080/uaa/authenticate
  limitedFunctionality:
    enabled: false
    whitelist:
      endpoints:
        - /oauth/authorize/**
        - /oauth/token/**
        - /check_token/**
        - /login/**
        - /login.do
        - /logout/**
        - /logout.do
        - /saml/**
        - /autologin/**
        - /authenticate/**
        - /idp_discovery/**
      methods:
        - GET
        - HEAD
        - OPTIONS
login:
  authorize:
    url: https://localhost:8080/uaa/oauth/authorize
  entityBaseURL: http://localhost:8080/uaa
  entityID: cloudfoundry-saml-login
  saml:
    assertionConsumerIndex: 0
    nameID: urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
    signMetaData: true
    signRequest: true
    socket:
      connectionManagerTimeout: 10000
      soTimeout: 10000
  selfServiceLinksEnabled: false
  serviceProviderCertificate: |
    -----BEGIN CERTIFICATE-----
    MIIEjzCCAvegAwIBAgIRAPSa1CxCun179dsELMAVNWUwDQYJKoZIhvcNAQELBQAw
    MzEMMAoGA1UEBhMDVVNBMRYwFAYDVQQKEw1DbG91ZCBGb3VuZHJ5MQswCQYDVQQD
    EwJjYTAeFw0xOTA2MTgyMjQ4MDJaFw0yMDA2MTcyMjQ4MDJaMD8xDDAKBgNVBAYT
    A1VTQTEWMBQGA1UEChMNQ2xvdWQgRm91bmRyeTEXMBUGA1UEAxMObG9jYWxob3N0
    OjgwODAwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQDMt7zNInryjy2S
    2qTxJbrb11Tp5LyCMOeeBOjEZyACuAfbrIinIiiyyeRMfqAEzA3T2sF28UYkP0JJ
    YHCqyUWLqIoYDw+cWDHDLhzhwqdbm3HLvS2dfTLQB4EpPHHneMq6mL+GFS8IKGFt
    4G6ZbQWmgAg35CSnXLfB4Bd1mjBdYvbQmLX2TdGLMbvHv/cBRnfMP98hpc6kX0CP
    nh0bWUBKHSOKodR88hriy3R0sjgQanQkIcqyTW6RBkiqGQHqTTsTxv7oeniH9Reg
    9TZ5nQ62AH0uVbIFukRJc6kZ3XIYizQ3hLjFupuFesnw/NkIMrop1nR8+bvy/6Uh
    hfLL06/lXCRMxqKKjqPOx5l+KgBzWE9knQ3PfWczd9P54g4AWSfG2YRBMXr67t1A
    PVAJWFtQ0T0wttQn/0eWCoGb2pDerMg3DlRrMEQKehHOm9PnN1cwAoPAQw/C+QX9
    sDOsfMWl1vMRcQy3lEPL3/v3heVxGI0HSB5671G9La0ITekfYxsCAwEAAaOBkTCB
    jjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/
    BAIwADAdBgNVHQ4EFgQUN9guVYcboFUixoU8xV1vXdnzZB8wHwYDVR0jBBgwFoAU
    34ho2O35hjEHhXCg+5W5B96LNDcwGQYDVR0RBBIwEIIObG9jYWxob3N0OjgwODAw
    DQYJKoZIhvcNAQELBQADggGBAAYMOIhedbhJQejb4lGIMxmbd0NVLB4hxC8Xg49A
    QWEKE7kOCuLiKUxBANCto7u8vIax34pJXMa+iKm5KJi+QQOEQ+zNJyScpiOcS7r+
    dTHh8j7Wqubnau6RRtZZj9N6QeX/FMoFxNxyK2Pb9DsVwM+JCJYD/M0sx6oSOkoi
    i2npMv3KBZRLn3Iv7A+xWlRuykEJONDvd9om5DiOANLk2RXtyX0NX4jU44toQIfu
    cRCanCy1mMJfuTTn65jnnKJshq2Br7pWRdkeoBMRgbRHqUX0u8Sm9hJ7gxiDxLus
    EVv94B+U9Ra9S/7FwW5lxNXsaKt6zFKbEf/mj6HRyCheBLkNoe+qCh1Yfp8pogrF
    VKXNTekOe05+EfFvMdZz+GeHMeV4RxucgJF4+9wlOPcOw8o8LXRqypTtgm/ar09L
    iI3flyH/IZHwJ0dUoqxM/L+rgSwLC2jdq49UC5hd52f4N5TB7su5J2y0ukj5ZHa3
    hlE42olbNEGcW5W9Ntgilqx1ZQ==
    -----END CERTIFICATE-----
  serviceProviderKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIG5AIBAAKCAYEAzLe8zSJ68o8tktqk8SW629dU6eS8gjDnngToxGcgArgH26yI
    pyIossnkTH6gBMwN09rBdvFGJD9CSWBwqslFi6iKGA8PnFgxwy4c4cKnW5txy70t
    nX0y0AeBKTxx53jKupi/hhUvCChhbeBumW0FpoAIN+Qkp1y3weAXdZowXWL20Ji1
    9k3RizG7x7/3AUZ3zD/fIaXOpF9Aj54dG1lASh0jiqHUfPIa4st0dLI4EGp0JCHK
    sk1ukQZIqhkB6k07E8b+6Hp4h/UXoPU2eZ0OtgB9LlWyBbpESXOpGd1yGIs0N4S4
    xbqbhXrJ8PzZCDK6KdZ0fPm78v+lIYXyy9Ov5VwkTMaiio6jzseZfioAc1hPZJ0N
    z31nM3fT+eIOAFknxtmEQTF6+u7dQD1QCVhbUNE9MLbUJ/9HlgqBm9qQ3qzINw5U
    azBECnoRzpvT5zdXMAKDwEMPwvkF/bAzrHzFpdbzEXEMt5RDy9/794XlcRiNB0ge
    eu9RvS2tCE3pH2MbAgMBAAECggGAfJN+//HwkXSRjiEhaGHGYQubb62zDSLHf8CL
    CSGcOCtXFNXcXqCJ1arIE8imheTKsVYYjtHqFhqsssxOI4/Rk1gfmN5paIG+3oBM
    MRHsF/HzAMGBZaoPZsp6TearhelarMxRGD4B3dv81glSJGlUm+qjladuqq3gYMmG
    XRlUPy/+9BdJ+7WFQ0gjdj2aCRuhwRhJJ0eoBRy1w++61K6uUauDulQaY2JM/CBF
    INJnDY5KWMZ7e59lHjmNtHz9TmBp8S4+rYJsMZaQJDtLLrw28MNncZtu5ZmYxhXn
    Ra9komDJ+s6ELDr74GlIbhh/FrndpAC7N89e1HbpL5OIEOX0BzwMPmUlKjy+rs8+
    JWoZdg3k83/rwzmWAB/InNKUQJwZ9ZQUFZYO4wM0YfxF0H7ZDauEg3et0QCEL7ZU
    OWmZFzGqbu3WteKd0pSx7RjiHTT79rJkgqrshSwp7dGyuB1uaY0ozgWlg9ZTYD46
    JoDisfKww5YajW2nAbYeB8op2hRhAoHBAOxn9B7b2BBbMBySNfVGbU1/sc/1kWT9
    coWugqLmKvjbkHXR/x1zUEPoGDj5ypcn42Tt0uI1ekbO7qERYQNB2lIyhl6A7oxL
    MkFzvItR0AtIdJj854g+ejHZ/IQUdf16Y3uS/b2ACyxO9khJqDxwSXUbXzHeZATp
    k9BEuFmoS62CIQ9gdOd1Sh0ZBHd6kqfAEf6PmqeiJWbSUOzb1dWAIIWi2vP1qUs1
    2+1ktguiMzw8xtDoULey9jS5CaZqpZDmywKBwQDdr2xISx9pQzJqniArWRC/YiRT
    DZF2ac4j1X9VVP6deNTE31aMUN7d/hfYHUOvwdhUcZm82ScrUnkh0GJUrDlBfEkP
    n5ewX+z0pLfjDvA4kJOoDUDTpgI14DXbAwNWWSfyN3mOcbYaKfl19FZRYSziv53Z
    fC5S+Bb4yCe8i6WEsyuXCTMtKrCP6EYHWsZpV+y7z2owtdI+KCNaM8UoBusqJ+VH
    +tyc3bbdgICOIcLW5K3tW5x3jAC+0xcoZaagmvECgcEAwkfwLMgZed+m22QhafA1
    9aHCnJhAo9FSI6C2BW/I0vmGb/1jfm19AkGkXnaSUsTaMODuFS9DzRtUqxPgOVAO
    Psz89n9ZC/zkUTvvMEPNCOjDwdLd6G8H9x4hUt6J1QWW6kBzvR+UjxZZejDmTL0u
    8UnMYuxUIGFhM6C2LCCOCQrPZparnGgcv2sG67XU/n1vjFeyDp/HwweGsBE+W5ZP
    o+OhsyoptgCOPDsvDMKA/rkn3xl89GrjwZJr5tLwO/QfAoHBALdoZFDnfiRriPG2
    w2y5smZ0vxLLnfZ3ESqKf1/NAx6rknUTRhqu6cSGbZnKlG58FQvANO6ORp7MDBXS
    vxfIqVIpjpTTd/9fTb8V7GF5wXs6+j7GQEUbCqciScxaEM/G0YrPJM2Z/Ixm/9H8
    BdIscKNk3ybJW9YfFXpctquCab2BMuYxoVqUACH/jLiW/KK5MM4ti3CjbT8pnB4L
    yOkV2Eg3W7WSsiVCNgHKSBHPktCRv+gprCkn9pHqOTWd7B7iMQKBwFSb15MBtYXX
    InarextGx55rrk08KTFKlbkYvFK2E6egNRtKkhN0oR8LanXyM8OnnQ8hwlxRn5ym
    WH4TbeJRzozyzmxd63EGJeuAHgmaMsvfUHCkAsyr75TzennAnOwANOmw5Hamp2j5
    y74pmF/wzzSpInhPJc16WOpt//2ic2XNUmvmkwSmliepTQfkXbuK9k5KkeMpkcXm
    OiGsNyt9U069vM8T6T1YvZ9rFwZZbhhD0PL1jYuMIp7B2BpN4JI0wQ==
    -----END RSA PRIVATE KEY-----
  serviceProviderKeyPassword: ""
  url: https://localhost:8080/uaa